changelog:
  categories:
    - title: "New Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Performance"
      labels:
        - "performance"
        - "perf"
    - title: "Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
