version: "3"
tasks:
  # CLI
  build:
    desc: Build the project in release mode (native Apple Silicon)
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/release/git-ai-cli
  build-debug:
    desc: Build the project in debug mode (native Apple Silicon)
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/debug/git-ai-cli
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  release:local:
    desc: Build release and install to user bin directory
    deps: [build]
    cmds:
      - cp target/release/git-ai ~/.local/bin/git-ai
      - chmod +x ~/.local/bin/git-ai

  debug:local:
    desc: Build release and install to user bin directory
    deps: [build-debug]
    cmds:
      - cp target/debug/git-ai ~/.local/bin/git-ai
      - chmod +x ~/.local/bin/git-ai

  test:e2e:
    desc: Run the end-to-end tests with debug build
    deps: [build-debug]
    cmds:
      - bats tests/e2e/user-scenarios.bats

  test:e2e:release:
    desc: Run the end-to-end tests with release build
    deps: [build]
    cmds:
      - bats tests/e2e/user-scenarios.bats

  install:
    desc: Install dependencies using Cargo
    cmds:
      - cargo install --path .